### ISSUE TITLE
Not all data is flushed when `.into_inner()` if `.flush()` wasn't called first

### ISSUE THREAD

**Issue by joshuawarner32** [alexcrichton/bzip2-rs#10]
It looks like when using a `writer::BzCompressor`, for certain buffer sizes, not all the output data gets correctly flushed.

I've added a failing test case to my fork here: https://github.com/joshuawarner32/bzip2-rs/blob/7628ede433bfd85059c6bb4f444bafb98c51ebda/src/writer.rs#L220 (that's just master on my fork, if you want to check it out).

I have yet to track that down to a specific problem - but the compressed size (131083 bytes, when flushing first, and 131072 bytes when not) lines up suspiciously with the buffer size in the writer (128*1024 = 131072 bytes).  The test-case has been minified (the input started at 10MB), so the close alignment is probably more of a red-herring.  I suspect being _over_ the buffer size is the real problem.

I'll look into it more this evening, and maybe open a PR.  I just wanted to give you a heads-up, in case you could spot the problem immediately.

**Comment by alexcrichton** [comment]
Ah yeah looks like a loop was forgotten, thanks for the report!
