### ISSUE TITLE
Is is possible to assume libbz2 is already linked?

### ISSUE THREAD

**Issue by micahsnyder** [alexcrichton/bzip2-rs#102]
I have a C static library that uses this crate.  My static lib links with a C program that is already linked with libbz2 (static or dynamic).  I don't need bzip2-sys to link with bzip2 - I just need it to assume it will be linked with bzip2.  Is that possible?

Presently I'm looking at this build failure on Windows:
```
  bz2.lib(bz2.dll) : error LNK2005: BZ2_bzDecompressInit already defined in clamav_rust.lib(bzlib.o)
  bz2.lib(bz2.dll) : error LNK2005: BZ2_bzDecompress already defined in clamav_rust.lib(bzlib.o)
  bz2.lib(bz2.dll) : error LNK2005: BZ2_bzDecompressEnd already defined in clamav_rust.lib(bzlib.o)
     Creating library libclamav\clamav.lib and object libclamav\clamav.exp
  libclamav\libclamav.dll : fatal error LNK1169: one or more multiply defined symbols found
```
ref: https://github.com/Cisco-Talos/clamav/actions/runs/8347839964/job/22848401392?pr=1183

**Comment by NobodyXu** [comment]
If you don't have libzip, then it would build a venderer version of it and statically linked with it, then yes, you don't need to link with it in your C library.

If you do have libzip dynlib, rhen you still need to link with it during link time.

**Comment by micahsnyder** [comment]
It looks to me like Rust is compiling bzlib into my static library, so it conflicts when my C library tries to link my Rust-built static library.

**Comment by micahsnyder** [comment]
This is a really weird build situation that I doubt anyone else will run into. To work around it, we switched to a pure-Rust decompressor (the bzip2-rs crate). So gonna close this ticket.
