### ISSUE TITLE
bzip2::write::{BzDecoder, BzEncoder} should implement get_ref/get_mut

### ISSUE THREAD

**Issue by sid0** [alexcrichton/bzip2-rs#15]
Concrete use case:

For my own code I want to implement `AsyncWrite` (from tokio-io) for `BzEncoder<W>` if `W: AsyncWrite`. For that I need to implement the `shutdown` method, which (since this is a wrapper) should call `shutdown` on the wrapped writer. Going to need a `get_mut` for that.

(Hopefully I can get to this myself -- still waiting on legal approval...)

**Comment by alexcrichton** [comment]
Yeah sounds great to me! I should have done these to start out with as well...

Lemme know if you end up being unable to take this on though as I'd also be more than happy to add the methods!
