### ISSUE TITLE
BzCompressor fails on empty buffer?

### ISSUE THREAD

**Issue by marcusklaas** [alexcrichton/bzip2-rs#3]
The `Read` implementation of `BzCompressor` can return an error when the underlying buffer return zero bytes: https://github.com/alexcrichton/bzip2-rs/blob/master/src/reader.rs#L67.

I believe this is now incorrect behaviour, as EOF is now signalled through a zero-byte read instead of an error. That's what I get from the docs, anyway: https://doc.rust-lang.org/std/io/trait.Read.html#tymethod.read

**Comment by alexcrichton** [comment]
Do you have a particular test case in mind? I did find the transition to `std::io` a bit tricky and I may have made a mistake!

**Comment by marcusklaas** [comment]
Here's a test case that fails for me. Doesn't actually fail on the compression, but the decompressed data isn't equal to the input..
    
    #[test]
    fn smoke3() {
        let m = vec![3u8; 128 * 1024 + 1];        
        let c = BzCompressor::new(&m[..], ::Compress::Default);
        let mut d = BzDecompressor::new(c);
        let mut data = vec![];
        d.read_to_end(&mut data).unwrap();
        assert!(data == &m[..]);
    }

**Comment by marcusklaas** [comment]
As a second test case (for which may not be the same issue), try compressing the pdf edition of LYAH: http://math.uni.lodz.pl/~kowalcr/PlockParad/learnyouahaskell.pdf

This produces an `InvalidInput` error for me:

    #[test]
    fn smoke4() {
        use std::fs::File;
        let mut file = File::open("learnyouahaskell.pdf").unwrap();
        let mut m = vec![];
        file.read_to_end(&mut m).unwrap();
        let mut c = BzCompressor::new(&m[..], ::Compress::Default);
        let mut data = vec![];
        assert!(c.read_to_end(&mut data).is_ok());
    }

**Comment by alexcrichton** [comment]
Hm interesting, I pushed [a recent change](https://github.com/alexcrichton/bzip2-rs/commit/00b7f69919b0d38f74eea1179f52faa4997b46b8) which shouldn't have changed semantics but both of your test cases work fine for me. Perhaps that change included a fix by accident? Could you test to see if git master works for you?

**Comment by marcusklaas** [comment]
Hmmm, that seems to have done the trick! Nice. I'm closing this then. Thanks!

P.S. It looks like you forgot to remove some `println!` statements ;-)
