### ISSUE TITLE
Error trying to install crate bzip2-sys

### ISSUE THREAD

**Issue by woubuc** [alexcrichton/bzip2-rs#33]
I'm trying to install the `zip` crate that depends on `bzip2` but I'm getting the following error.

Using Rust nightly 1.31.0 ("2018 edition")

```
Compiling bzip2-sys v0.1.6
error: failed to run custom build command for `bzip2-sys v0.1.6`
process didn't exit successfully: `C:\Dev\[project]\target\debug\build\bzip2-sys-33f8cb5c7dfcf9ea\build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-pc-windows-msvc")
OPT_LEVEL = Some("0")
HOST = Some("x86_64-pc-windows-msvc")
CC_x86_64-pc-windows-msvc = None
CC_x86_64_pc_windows_msvc = None
HOST_CC = None
CC = Some("C:\\mingw-w64\\x86_64-7.3.0-posix-seh-rt_v5-rev0\\mingw64\\bin\\gcc.exe")
CFLAGS_x86_64-pc-windows-msvc = None
CFLAGS_x86_64_pc_windows_msvc = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")
running: "C:\\mingw-w64\\x86_64-7.3.0-posix-seh-rt_v5-rev0\\mingw64\\bin\\gcc.exe" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "bzip2-1.0.6" "-D_WIN32" "-DBZ_EXPORT" "-DBZ_NO_STDIO" "/FoC:\\Dev\\[project]\\target\\debug\\build\\bzip2-sys-351245291296f0d0\\out\\bzip2-1.0.6\\blocksort.o" "/c" "bzip2-1.0.6/blocksort.c"
cargo:warning=gcc.exe: error: /FoC:\Dev\[project]\target\debug\build\bzip2-sys-351245291296f0d0\out\bzip2-1.0.6\blocksort.o: Invalid argument
cargo:warning=gcc.exe: error: /c: No such file or directory
exit code: 1

--- stderr
thread 'main' panicked at '

Internal error occurred: Command "C:\\mingw-w64\\x86_64-7.3.0-posix-seh-rt_v5-rev0\\mingw64\\bin\\gcc.exe" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "bzip2-1.0.6" "-D_WIN32" "-DBZ_EXPORT" "-DBZ_NO_STDIO" "/FoC:\\Dev\\[project]\\target\\debug\\build\\bzip2-sys-351245291296f0d0\\out\\bzip2-1.0.6\\blocksort.o" "/c" "bzip2-1.0.6/blocksort.c" with args "gcc.exe" did not execute successfully (status code exit code: 1).

', C:\Users\[user]\.cargo\registry\src\github.com-1ecc6299db9ec823\cc-1.0.25\src\lib.rs:2260:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by alexcrichton** [comment]
Thanks for the report! It looks, though, like you're compiling for MSVC but you've set `CC` to a MinGW compiler. Did you mean to compile for MinGW?

**Comment by woubuc** [comment]
I have both MSVC and MinGW installed, so it should be able to use either one. `which g++` gives me the MinGW one, I'm not sure how I can check which one Cargo uses? Everything else I've tried builds fine with `cargo build`, only this crate gives an error.

**Comment by alexcrichton** [comment]
The `cc` crate, which configures compilers, is reading the explicitly set `CC` env var and that overrides the default compiler, `cl.exe`, for the MSVC target. If you want this to "just work" when compiling for MSVC you'll need to unset the `CC` env var.

**Comment by woubuc** [comment]
Unsetting the CC env did solve it, thanks!

**Comment by dnbaker** [comment]
In case anyone else runs into this, apparently, on OSX, if AR is set, it is likely to cause build issues. Unsetting it (and CC) solves this problem.

**Comment by madprogramer** [comment]
> In case anyone else runs into this, apparently, on OSX, if AR is set, it is likely to cause build issues. Unsetting it (and CC) solves this problem.

Installing cctools from Mac Ports seems to do the trick!

**Comment by woubuc** [comment]
> Hey! Complete noob here. What does it mean to set AR and CC? Where are they (AR & CC) set? Thanks for any help.

We're talking about **environment variables** (often called 'env' for short). These are system-wide global variables that can be read by all applications on your machine, `CC` for example is used by some programs to point to an installed C compiler.

Each OS has a different way to manage them, you can look up 'how to set environment variables on [your system]' to find out how to do this.
