### ISSUE TITLE
Yank breaking versions with "*" deps

### ISSUE THREAD

**Issue by kornelski** [alexcrichton/bzip2-rs#52]
Some old versions of `bzip2` have dependencies specified with `"*"` version requirement (bzip2-sys = "*").

Because these old versions of `bzip2` are unusable in practice, and cause problems for the `minimal-versions` Cargo feature, I suggest yanking them:

```bash
cargo yank --vers 0.0.1
cargo yank --vers 0.0.2
cargo yank --vers 0.0.3
```

**Comment by kornelski** [comment]
Same for `bzip2-sys`


```bash
cargo yank --vers 0.0.1
```

**Comment by alexcrichton** [comment]
Thanks for the report, but I do not have time to manage extremely old versions of this crate, so I'm going to close this.
