### ISSUE TITLE
failed to run custom build command for `bzip2-sys v0.1.8+1.0.8`

### ISSUE THREAD

**Issue by eminfan** [alexcrichton/bzip2-rs#57]
I stucked by this error, pls help me.

_` Compiling bzip2-sys v0.1.8+1.0.8
   Compiling bincode v1.2.1
   Compiling serde_derive v1.0.110
   Compiling chrono v0.4.11
error: failed to run custom build command for `bzip2-sys v0.1.8+1.0.8`

Caused by:
  process didn't exit successfully: `D:\projects\write-teacher-master\miniprogram-write-teacher-master\teacher\target\release\build\bzip2-sys-a0175bb02427920c\build-script-build` (exit code: 1)
--- stderr

error occurred: Command "cmd" "/c" "emcc.bat" "-Os" "-ffunction-sections" "-fdata-sections" "-fPIC" "-I" "bzip2-1.0.8" "-D_FILE_OFFSET_BITS=64" "-DBZ_NO_STDIO" "-o" "D:\\projects\\write-teacher-master\\miniprogram-write-teacher-master\\teacher\\target\\asmjs-unknown-emscripten\\release\\build\\bzip2-sys-372a0e1a0c44a99a\\out\\lib\\bzip2-1.0.8/blocksort.o" "-c" "bzip2-1.0.8/blocksort.c" with args "cmd" did not execute successfully (status code exit code: 1)._

`

**Comment by alexcrichton** [comment]
Thanks for the report, but this looks like a native toolchain error with Emscripten and likely unrelated to this crate, so I don't think I can be of too much help here.

**Comment by eminfan** [comment]
> Thanks for the report, but this looks like a native toolchain error with Emscripten and likely unrelated to this crate, so I don't think I can be of too much help here.
Thank you for your reply. I will learnEmscripten more.

**Comment by eminfan** [comment]
Thank you for your reply. I will learnEmscripten more.

**Comment by eminfan** [comment]
when I run it again on linux，it succeeded. If anyone met this bug,do not use windows.
