### ISSUE TITLE
Decompression stops silently on byte #900000

### ISSUE THREAD

**Issue by ygyzys** [alexcrichton/bzip2-rs#75]
I got this using this file: https://database.lichess.org/atomic/lichess_db_atomic_rated_2015-01.pgn.bz2 (I checked at least one other file, and it also stopped on 900000th byte)
The following code:
```rust
use std::fs::File;
use std::io;

fn by_bzip2() -> std::io::Result<()> {
    let compressed_file = File::open("lichess_db_atomic_rated_2015-01.pgn.bz2")?;
    let mut decompressed_output = File::create("decoded_by_bzip2.pgn")?;

    let mut reader = bzip2::read::BzDecoder::new(compressed_file);
    io::copy(&mut reader, &mut decompressed_output)?;
    Ok(())
}

fn by_bzip2_rs() -> std::io::Result<()> {
    let compressed_file = File::open("lichess_db_atomic_rated_2015-01.pgn.bz2")?;
    let mut decompressed_output = File::create("decoded_by_bzip2-rs.pgn")?;

    let mut reader = bzip2_rs::DecoderReader::new(compressed_file);
    io::copy(&mut reader, &mut decompressed_output)?;
    Ok(())
}

fn main() {
    by_bzip2().expect("bzip2");
    by_bzip2_rs().expect("bzip2-rs");
}
```
returns 0 on exit, produces same files `decoded_by_bzip2.pgn` and `decoded_by_bzip2-rs.pgn` each of length exactly 900000 bytes, which are a prefix of a much larger file that my system decoder `/usr/bin/bzip2 -dk lichess_db_atomic_rated_2015-01.pgn.bz2` produces. So the decoding in both `bzip2` and `bzip2-rs` crates for some reason abruptly stops on this round number 900000 without printing any error message. Which looks like a bug in the crates, not in the file itself, since the file is handled correctly by Linux utilities.

**Comment by paolobarbolini** [comment]
Hello, speaking for the `bzip2-rs` crate the issue is that this file is a [multistream bzip2 file](https://chaosinmotion.com/2011/07/29/and-another-curiosity-multi-stream-bzip2-files/), which the decoder doesn't support, because it stops when the first end-of-file is reached. You can verify that by putting a println [here](https://github.com/paolobarbolini/bzip2-rs/blob/72ff918cee676e8458ff12f09a1199649df45923/src/decoder/block/mod.rs#L184) and you'll see the end-of-stream is reached even though the end of file hasn't been reached yet.

**Comment by ygyzys** [comment]
@paolobarbolini  Hello, thanks for reply. I want to add it to `bzip2-rs`, but it seems to be a breaking change. In my view, we should remove `ReadState::Eof` entirely, since `Decoder` can never know that the end of file happened (it can only know that the end of block happened). Instead, `DecoderReader` should check for the end of file in the original stream (which it doesn't do now, and actually it seems to me that it can get stuck in infinite loop of feeding zero bytes to `Decoder` on some corrupted files which contain the header but end abruptly).

In any case, I'm more interested in pure Rust crate, so I suggest to create an issue there and continue our discussion of this there if possible.

And btw, I found a place where it is handled in the reference implementation: https://gitlab.com/federicomenaquintero/bzip2/-/blob/master/bzip2.c#L455 If you change this line to unconditional `break;`, bzip2 starts to give identical result to these crates.

**Comment by paolobarbolini** [comment]
I opened an issue over at my repo https://github.com/paolobarbolini/bzip2-rs/issues/5 @ygyzys.

**Comment by ygyzys** [comment]
OK, and I'll close the issue here, because I missed that there is a `MultiBzDecoder` class in this crate. A bit confusing though: I don't see any reason why this should be a separate class from `BzDecoder`, since its functionality is strictly superior, and performance overhead for checking the end of block is hardly an issue.
